name: tugasbesar_2172008
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.2 <4.0.0'

dependencies:
  assets: ^0.0.1
  build_runner: ^2.4.6
  camera: ^0.10.5+9
  curved_navigation_bar: ^1.0.3
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.3.10
  intl: ^0.18.1
  qr_code_dart_scan: ^0.7.3
  qr_code_scanner: ^1.0.1
  riverpod: ^2.4.8
  riverpod_annotation: ^2.1.4
  supabase: ^1.11.11

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  riverpod_generator: ^2.3.1
  riverpod_lint: ^2.0.3

flutter:
  uses-material-design: true
  assets:
    - lib/assets/images/cash.png
    - lib/assets/images/request.png
    - lib/assets/images/history.png
    - lib/assets/images/add.png
    - lib/assets/images/money.png
    - lib/assets/images/index.jpeg
    - lib/assets/images/shope.jpeg
    - lib/assets/images/tokped.jpeg
